#!/bin/bash
clear
echo -e ""
echo -e "                                ™RIDWAN-STORE™ "
echo -e ""
echo -e "✫========================-©Menu-Ridwan©-========================✫"
echo -e "* menu         : List of Main Commands"
echo -e "  Scrip          : By Ridwan - Store"
echo -e "✫===================-©SSH/WSSH & OpenVPN©-=====================✫"
echo -e ""
echo -e "* user-new     : Create SSH & OpenVPN Account"
echo -e "* trial        : Generate SSH & OpenVPN Trial Account"
echo -e "* renew        : Extending SSH & OpenVPN Account Active Life"
echo -e "* deleteuser   : Delete SSH & OpenVPN Account"
echo -e "* check        : Check User Login SSH & OpenVPN"
echo -e "* member       : Daftar Member SSH & OpenVPN"
echo -e "* delete       : Delete User Expired SSH & OpenVPN"
echo -e "* autokill     : Set up Autokill SSH"
echo -e "* checkuser    : Displays Users Who Do Multi Login SSH"
echo -e "* restart      : Restart Service Dropbear, Squid3, OpenVPN and SSH"
echo -e ""
echo -e "✫========================-©MENU-WG©-========================✫"
echo -e ""
echo -e "* add-wg       : Create Wireguard Account"
echo -e "* del-wg       : Delete Wireguard Account"
echo -e "* renew-wg     : Extending Wireguard Account Active Life"
echo -e ""
echo -e "✫========================-©MENU-L2TP©-========================✫"
echo -e ""
echo -e "* add-l2tp     : Creating L2TP Account"
echo -e "* del-l2tp     : Deleting L2TP Account"
echo -e "* renew-l2tp   : Extending L2TP Account Active Life"
echo -e ""
echo -e "✫========================-©MENU-PPTP©-========================✫"
echo -e ""
echo -e "* add-pptp     : Create Account PPTP"
echo -e "* del-pptp     : Delete PPTP Account"
echo -e "* renew-pptp   : Extending PPTP Account Active Life"
echo -e "* check-pptp   : Check User Login PPTP"
echo -e ""
echo -e "✫========================-©MENU-SSTP©-========================✫"
echo -e ""
echo -e "* add-sstp     : Create Account SSTP"
echo -e "* del-sstp     : Delete SSTP Account"
echo -e "* renew-sstp   : Extending SSTP Account Active Life"
echo -e "* check-sstp   : Check User Login SSTP"
echo -e ""
echo -e "✫========================-©MENU-SSR©-========================✫"
echo -e ""
echo -e "* add-ssr      : Create SSR Account"
echo -e "* del-ssr      : Deleting SSR Account"
echo -e "* renew-ssr    : Extending SSR Account Active Life"
echo -e ""
echo -e "✫=======================-©MENU-SSHOCK©-=======================✫"
echo -e ""
echo -e "* add-ss       : Creating Shadowsocks Account"
echo -e "* del-ss       : Delete Shadowsocks Account"
echo -e "* renew-ss     : Extending Shadowsocks Account Active Life"
echo -e "* check-ss     : Check User Login Shadowsocks"
echo -e ""
echo -e "✫========================-©MENU-V2RAY©-========================✫"
echo -e ""
echo -e "* add-ws       : Create V2RAY Vmess Websocket Account"
echo -e "* del-ws       : Deleting V2RAY Vmess Websocket Account"
echo -e "* renew-ws     : Extending Vmess Account Active Life"
echo -e "* check-ws     : Check User Login V2RAY"
echo -e "* cert2vray    : Renew Certificate V2RAY Account"
echo -e ""
echo -e "✫========================-©MENU-VLESS©-========================✫"
echo -e ""
echo -e "* add-vless    : Create V2RAY Vless Websocket Account"
echo -e "* del-vless    : Deleting V2RAY Vless Websocket Account"
echo -e "* renew-vless  : Extending Vless Account Active Life"
echo -e "* check-ws     : Check User Login V2RAY"
echo -e ""
echo -e "✫=======================-©MENU-TROJAN©-=======================✫"
echo -e ""
echo -e "* add-tr       : Create Trojan Account"
echo -e "* del-tr       : Deleting Trojan Account"
echo -e "* renew-tr     : Extending Trojan Account Active Life"
echo -e "* check-tr     : Check User Login Trojan"
echo -e ""
echo -e "✫=======================-©MENU-SYSTEM©-=======================✫"
echo -e ""
echo -e "* add-host     : Add Or Change Subdomain Host For VPS"
echo -e "* change-port  : Change Port of Some Service"
echo -e "* wbmn         : Webmin Menu"
echo -e "* kernel-updt  : Update To Latest Kernel"
echo -e "* limit-speed  : Limit Bandwith Speed Server"
echo -e "* ram          : Check Usage of VPS Ram"
echo -e "* reboot       : Reboot VPS"
echo -e "* speedtest    : Speedtest VPS"
echo -e "* update       : Update To Latest Script Version"
echo -e "* info         : Displaying System Information"
echo -e "* about        : Info Script Auto Install"
echo -e "* exit         : Exit From VPS "
echo -e ""
echo -e "✫=======================-©SCRIP-RIDWAN©-=======================✫"
echo -e ""
